name: geo4520
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - alabaster=0.7.12=py37_0
  - asn1crypto=0.24.0=py37_0
  - astroid=2.2.5=py37_0
  - attrs=19.1.0=py37_1
  - babel=2.7.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - bokeh=1.3.4=py37_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2019.8.28=0
  - cairo=1.14.12=h8948797_3
  - cartopy=0.16.0=py37hfa13621_0
  - certifi=2019.9.11=py37_0
  - cffi=1.12.3=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - click=7.0=py37_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py37_0
  - cloudpickle=1.2.2=py_0
  - cmarkgfm=0.4.2=py37h7b6447c_0
  - cryptography=2.3.1=py37hc365091_0
  - curl=7.61.0=h84994c4_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.0=py37h7b6447c_0
  - dask-core=2.4.0=py_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py37_1
  - defusedxml=0.6.0=py_0
  - descartes=1.1.0=py_3
  - distributed=2.4.0=py_0
  - docutils=0.15.2=py37_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - ezodf=0.3.2=py_2
  - ffmpeg=3.4=h7985aa0_0
  - fiona=1.7.12=py37h3f37509_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - freexl=1.0.5=h14c3975_0
  - fsspec=0.5.1=py_0
  - future=0.17.1=py37_0
  - gdal=2.2.4=py37h04863e7_1
  - geopandas=0.4.1=py_0
  - geos=3.6.2=heeff764_2
  - giflib=5.1.4=h14c3975_1
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - graphite2=1.3.13=h23475e2_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.8.18=h6792536_1
  - heapdict=1.0.1=py_0
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py37_0
  - imageio=2.5.0=py37_0
  - imagesize=1.1.0=py37_0
  - intel-openmp=2019.4=243
  - ipykernel=5.1.2=py37h39e3cac_0
  - ipython=7.8.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py37_0
  - jasper=2.0.14=h07fcdf6_1
  - jedi=0.15.1=py37_0
  - jeepney=0.4.1=py_0
  - jinja2=2.10.1=py37_0
  - joblib=0.13.2=py37_0
  - jpeg=9b=h024ee3a_2
  - json-c=0.13.1=h1bed415_0
  - jsonschema=3.0.2=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.3.3=py37_1
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.5.0=py_0
  - kealib=1.4.7=h5472223_5
  - keyring=18.0.0=py37_0
  - kiwisolver=1.1.0=py37he6710b0_0
  - krb5=1.16.1=hc83ff2d_6
  - lazy-object-proxy=1.4.2=py37h7b6447c_0
  - libboost=1.67.0=h46d08c1_4
  - libcurl=7.61.0=h1ad7b7a_0
  - libdap4=3.19.1=h6ec2957_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgdal=2.2.4=heea9cce_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libiconv=1.15=h63c8f33_5
  - libkml=1.3.0=h590aaf7_4
  - libnetcdf=4.6.1=h015f1c5_0
  - libopencv=3.4.1=he6673a0_3
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libpq=10.5=h1ad7b7a_0
  - libprotobuf=3.5.2=h6f1eeef_0
  - libsodium=1.0.16=h1bed415_0
  - libspatialindex=1.8.5=h20b78c2_2
  - libspatialite=4.3.0a=he475c7f_19
  - libssh2=1.8.0=h9cfc8f7_4
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - libxslt=1.1.33=h7d1a2b0_0
  - llvmlite=0.29.0=py37hd408876_0
  - locket=0.2.0=py37_1
  - lxml=4.4.1=py37hefd8a0e_0
  - mapclassify=2.0.1=py_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.1=py37h5429711_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.14=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - msgpack-python=0.6.1=py37hfd86e86_1
  - munch=2.3.2=py37_0
  - nbconvert=5.6.0=py37_1
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=he6710b0_1
  - netcdf4=1.4.1=py37h083d9da_0
  - notebook=6.0.1=py37_0
  - numba=0.45.1=py37h962f231_0
  - numpy=1.17.2=py37haad9e8e_0
  - numpy-base=1.17.2=py37hde5b4d6_0
  - numpydoc=0.9.1=py_0
  - odfpy=1.4.0=py_1
  - olefile=0.46=py37_0
  - opencv=3.4.1=py37h40b0b35_3
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.0.2t=h7b6447c_1
  - owslib=0.18.0=py_0
  - packaging=19.2=py_0
  - palettable=3.3.0=py_0
  - pandas=0.25.1=py37he6710b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.5.1=py_0
  - partd=1.0.0=py_0
  - patsy=0.5.1=py37_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pixman=0.38.0=h7b6447c_0
  - pkginfo=1.5.0.1=py37_0
  - poppler=0.65.0=h581218d_1
  - poppler-data=0.4.9=0
  - proj4=5.0.1=h14c3975_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py37_0
  - psutil=5.6.3=py37h7b6447c_0
  - psycopg2=2.7.5=py37hb7f436b_0
  - ptyprocess=0.6.0=py37_0
  - py-opencv=3.4.1=py37he6673a0_3
  - pycodestyle=2.5.0=py37_0
  - pycparser=2.19=py37_0
  - pyepsg=0.4.0=py37_0
  - pyflakes=2.1.1=py37_0
  - pygments=2.4.2=py_0
  - pylint=2.3.1=py37_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.2=py_0
  - pyproj=1.9.5.1=py37h7b21b82_1
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.15.4=py37h7b6447c_0
  - pysal=2.0.0=py_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py37_0
  - python=3.7.0=h6e4f718_3
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.2=py_0
  - pyyaml=5.1.2=py37h7b6447c_0
  - pyzmq=18.1.0=py37he6710b0_0
  - qt=5.9.6=h8703b6f_2
  - qtawesome=0.6.0=py_0
  - qtconsole=4.5.5=py_0
  - qtpy=1.9.0=py_0
  - readline=7.0=h7b6447c_5
  - readme_renderer=24.0=py37_0
  - requests=2.22.0=py37_0
  - requests-toolbelt=0.9.1=py_0
  - rope=0.14.0=py_0
  - rtree=0.8.3=py37_0
  - scikit-learn=0.21.3=py37hd81dba3_0
  - scipy=1.3.1=py37h7c811a0_0
  - seaborn=0.9.0=py37_0
  - secretstorage=3.1.1=py37_0
  - send2trash=1.5.0=py37_0
  - setuptools=41.2.0=py37_0
  - shapely=1.6.4=py37h7ef4460_0
  - simplegeneric=0.8.1=py37_2
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - snowballstemmer=1.9.1=py_0
  - sortedcontainers=2.1.0=py37_0
  - sphinx=2.2.0=py_0
  - sphinxcontrib=1.0=py37_1
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - sphinxcontrib-websupport=1.1.2=py_0
  - spyder=3.3.6=py37_0
  - spyder-kernels=0.5.2=py37_0
  - sqlalchemy=1.3.8=py37h7b6447c_0
  - sqlite=3.29.0=h7b6447c_0
  - statsmodels=0.10.1=py37hdd07704_0
  - tblib=1.4.0=py_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py37_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37h7b6447c_0
  - tqdm=4.36.1=py_0
  - traitlets=4.3.2=py37_0
  - twine=2.0.0=py_0
  - urllib3=1.24.2=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.11.2=py37h7b6447c_0
  - wurlitzer=1.0.3=py37_0
  - xarray=0.13.0=py_0
  - xerces-c=3.2.2=h780794e_0
  - xlrd=1.2.0=py37_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zict=1.0.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - cftime==1.0.2.1
    - cython==0.29
    - dask==0.19.4
    - dill==0.2.9
    - h5py==2.8.0
    - inspyred==1.0.1
    - llc==0.2.0
    - networkx==2.2
    - nose==1.3.7
    - opencv-python==3.4.3.18
    - pillow==5.3.0
    - pip==19.1.1
    - pkgconfig==1.4.0
    - pybob==0.25
    - pykml==0.1.3
    - pykrige==1.4.1
    - pykriging==0.2.0
    - pyvips==2.1.4
    - pywavelets==1.0.1
    - ruptures==1.0.1
    - scikit-gstat==0.2.5
    - scikit-image==0.15.0
    - sphinx-argparse==0.2.5
    - sphinx-rtd-theme==0.4.3

